### model
model_name_or_path: /mnt/afs/hfmodel/deepseek-coder-33b-instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: python_code_instructions_18k_alpaca,self-oss-instruct-sc2-exec-filter-50k,glaive_code_assistant_v3,synth_vuln_fixes,our_gpt4_gen_100,our_gpt4_gen_100_1
template: deepseek
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/afs/ljl/codehit/003/saves/deepseek-coder-33b-instruct/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
