### model
model_name_or_path: /mnt/afs/hfmodel/Qwen2.5-Coder-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset synthe_triton_all,crawl_triton_all_simpleInstru,crawl_triton_all_complexInstru,crawl_triton_hard_complexInstru
dataset: synthe_triton_all
template: qwen
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/afs/ljl/triton_exps/qwen2.5_coder_7b-instru/synthe
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
